### PR TITLE
Match json schema

### PR DESCRIPTION
**Pull request by samiir95**

### CODE REVIEW

**Comment by samiir95** [comment]
I don't know why this error is appeared although I've updated this below
version from 3.0.0 to  4.4.0 pkg:maven/io.rest-assured/json-schema
***@***.***

**Review by MohabMohie — APPROVED** [review]
This is an excellent contribution! Thank you :)
for the future kindly consider adding at least one test to show how the new method should look.

**Comment by samiir95** [comment]
> This is an excellent contribution! Thank you :) for the future kindly consider adding at least one test to show how the new method should look.

Okay and here's **the whole test** that I created to test this method. Thank you for your continuous support <3 
image

**Comment by MohabMohie** [comment]
Well since you have it already, kindly create a PR to merge it in to the related src/test/java package.

Those tests run with every new change as user journey tests for the engine to ensure that nothing breaks... So it's very healthy to have tests for every new feature.

**Comment by samiir95** [comment]
> Well since you have it already, kindly create a PR to merge it in to the related src/test/java package.
> 
> Those tests run with every new change as user journey tests for the engine to ensure that nothing breaks... So it's very healthy to have tests for every new feature.

I've uploaded a new pull request for it, Kindly check it. Thank you!

**Pull request merged**
